version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: ssingamneni/udagram-reverseproxy:prod
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: ssingamneni/udagram-restapi-user:prod
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: ssingamneni/udagram-restapi-feed:prod

  backend_feed:
    build:
      context: ../../udacity-c3-restapi-email 
    image: ssingamneni/udagram-restapi-email:prod
  frontend:
    build:
      context: ../../udacity-c3-frontend  
    image: ssingamneni/udagram-frontend:prod
